# ARRAY FUNCTIONS
 We implement Array Operations in "NUMPY ARRAYS" are   
    1.zeros()         
    2.ones()        
    3.reshape()      
    4.arrange()       
    5.linspace()      
    6.zeros_like()      
    7.ones_like()     
    8.full_like()     
    9.eye()      
    10.empty()      
    11.empty_like()     
    12.identify()     

# zeros()
  -->It returns a new Array with "Shape" & "Type" filled with 0's.   
    formula ==zeros([row,column],dtype=int,order='c')

In [8]:
import numpy as n
a=n.zeros([2,2],dtype=int)
print(a,type(a))

[[0 0]
 [0 0]] <class 'numpy.ndarray'>


# Ones()
 -->Its Returns an Array filled with 1's.   

In [9]:
import numpy as n
a=n.ones([2,3],dtype=int)
print(a)

[[1 1 1]
 [1 1 1]]


# reshape()
  -->it is used to convert one dimensional array to another dimensional

In [7]:
import numpy as p
a=p.array((10,20,30,40,50))
b=a.reshape(5,1)
print(b)

[[10]
 [20]
 [30]
 [40]
 [50]]


# arange() 
 --->array function which displays how many array values are to Present in a Array.  
  formula== arange(Start,Stop[end+1]). 

In [6]:
import numpy as p
a=p.arange(2,7)
print(a)
b=p.arange(2,8) #(start ,end+1)
print(b)


[2 3 4 5 6]
[2 3 4 5 6 7]


# linspace()
-->linear space it contains multiple values in array and it returns in a linear form .   
 Formula == linspace(Start,Stop,num=10,endpoint=True,dtype)

In [19]:
import numpy as p
a=p.linspace(3,5,10)
print(a)
print("\n")
print("---starting from 0\n")
b=p.linspace(0,1,5)
print(b)
print("\n")
print("Starting from points\n")
a=p.linspace(0.9,1,5)
print(a)
print("\n")
print("Starting & stop from points\n")
a=p.linspace(0.9,0.8,5)
print(a)


[3.         3.22222222 3.44444444 3.66666667 3.88888889 4.11111111
 4.33333333 4.55555556 4.77777778 5.        ]


---starting from 0

[0.   0.25 0.5  0.75 1.  ]


Starting from points

[0.9   0.925 0.95  0.975 1.   ]


Starting & stop from points

[0.9   0.875 0.85  0.825 0.8  ]


# zero_like()
 ---> these will returns the value in array with 0's in Linear Form.

In [21]:
import numpy as m
a=m.zeros_like((3,2))
print(a)
a=m.zeros_like((3,2,10,20,55,4))
print(a)

[0 0]
[0 0 0 0 0 0]


# ones_like() 
---->it returns an array in a linear way,count of the array values

In [22]:
import numpy as m
a=m.ones_like((3,2))
print(a)
a=m.ones_like((3,2,10,20,55,4))
print(a)

[1 1]
[1 1 1 1 1 1]


# full_like()
    -->it returns a new array with the same shape and type

In [27]:
import numpy as m
a=m.full_like((3,2),5.5,dtype=float)
print(a)
a=m.full_like((3,2,10,20,55,4),5.5,dtype=float)
print(a)

[5.5 5.5]
[5.5 5.5 5.5 5.5 5.5 5.5]


# eye()
  -->it is 2D array it fill 1's in Diagonal rest in 0's 

In [29]:
import numpy as m
a=m.eye(5) # nothing but 5x5 matrix (diagonal all are 1's)
print(a)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# empty()
---> It returns all the Values as Empty by default 0's

In [6]:
import numpy as m
a=m.empty((3,2),dtype=float) # it accepts all elements as default
print(a)
print("\n")
print("In integer format")
print("\n")
a=m.empty([4,2],dtype=int)
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In integer format


[[       1        1]
 [       0  5374021]
 [     988        0]
 [16777984      523]]


# empty_like() 
  --->linear format

In [44]:
import numpy as m
a=m.empty_like((3,2),dtype=float)
print(a)
print("\n")
a=m.empty_like((2,2,4,5,5,7,7),dtype=int)
print(a)

[1. 1.]


[2 2 4 5 5 7 7]


# identity()
--->it returns all the values 1's in diagonal and  0's in rest positions like eye() function.

In [42]:
import numpy as m
a=m.identity(5) # it returns the same origianl array as a output bu coping.
print(a)
print("\n")
print(" if the values are 2\n")
import numpy as m
a=m.identity(2)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


 if the values are 2

[[1. 0.]
 [0. 1.]]


# BROADCASTING EXAMPLE

In [10]:
import numpy as n
a=n.array(((1,2,3),(4,5,6),(7,8,9),(10,11,12)))
b=n.array((1,0,1))
c=n.empty_like(a)
for i in range(4):
    c[i,:]=a[i,:]+b
print(a)
print("\n")
print("After adding the values to all the 2d array elements we get as---")
print("\n")
print(c)    

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


After adding the values to all the 2d array elements we get as---


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
