# PANDAS

its a one of the Python Library where (pandas-->pan--panal and Das--data) nothing but Panal Data.

PANAL DATA :      
      -->the data which is arranged in the form of Tables.        
      -->in panal data it contains any type of data.            
      -->In panal data ,data is may be NAN(not a None-it may contains MissValue).

# USE OF PANDAS

The main purpose of pandas is to find the relation between 2 or more columns in a table for the purpose of statistical Operations( where in pictorial like graph representing of the data from table related ) 

# PANDAS PACKAGE

It is a Group of PanalData which are offering to analyze the data(Labelled Data--labelled details and Relational Data--table format).

# Types of pandas Packages

                       DATA STRUCTURE
                        /          \
                       /            \
                   1.SERIES      2.DATAFRAME
   
SERIES :   
      -->a Series is a one dimensional labelled data DS.   
      -->The axis of Labelled data is known as indexes.    
      -->series are nothing but Columns in Excel Sheet.   
      
CREATING SERIES:     
    -->Panda_Obj.Series(Collection-Name)   
    # collection should be single dimenstion(are list,tuble,set,arrays,numpy).

In [7]:
import pandas as n
a=('CS','NM','MV','NS') 
b=n.Series(a)   
print(b)
# all are arranged in a coloumn with indexes and also if there is no x axis also y axis will be present in it.Because it 
#is a C-1Dimnesion ,0 and R-can change.

0    CS
1    NM
2    MV
3    NS
dtype: object


#            ACCESSING PANDA SERIES ELEMENTS
                 /                   \
                /                     \
     1.ACCESS WITH POSITIONS        2.ACCESS WITH INDEX
        (NORAML INDEX VALUES)   

In [1]:
import pandas as n
a=('CS','NM','MV','NS') 
b=n.Series(a)
print(b)
print("\n")
print("ACCESS WITH POSITION")
print(b[1:3])
print("\n")
print(b[-4::3])
print("\n")
print("ACCESS WITH INDEX")
c=n.Series(b,index=['a','b','n','m']) #it doesnot work due to it takes dublicate values of the series
                                      #is copying to another varable c .so that's why it gives the output values as NAN 
print(c)
print(c['m'])

0    CS
1    NM
2    MV
3    NS
dtype: object


ACCESS WITH POSITION
1    NM
2    MV
dtype: object


0    CS
3    NS
dtype: object


ACCESS WITH INDEX
a    NaN
b    NaN
n    NaN
m    NaN
dtype: object
nan


In [12]:
a=('CS','NM','MV','NS') 
b=n.Series(a,index=[1,2,3,4])
print(b)

1    CS
2    NM
3    MV
4    NS
dtype: object


10,20,30,40
0,1,2,3
[0:2]

In [15]:
a=('CS','NM','MV','NS') 
b=n.Series(a,index=['a','b','n','m']) # here copying is not done only one variable is arranged 
                                     # in a series that only printed here without copying that 
                                      #series values into another values.
print(b)
print(b['m'])

a    CS
b    NM
n    MV
m    NS
dtype: object
NS


In [16]:
import numpy as n
a=n.array((((1,2,3),(4,5,6),(7,8,9),(10,11,12))))
b=n.array((1,0,1))
c=n.empty_like(a)
for i in range(4):
    c[i,:]=a[i,:]+b
print(a)
print("\n")
print("After adding the values to all the 2d array elements we get as---")
print("\n")
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


After adding the values to all the 2d array elements we get as---


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [18]:
import numpy as np
a= np.array(((1, 2, 3), (4, 5, 6), (7, 8, 9), (10, 11, 12)))
b= np.array((1, 0, 1))
# Expand the dimensions of b to match the shape of a
b_expan = b[:, np.newaxis]
# Use broadcasting to add b to each row of a
c_broadcasted = a + b_expan
print("Original 2D array a:")
print(a)
print("\n")
print("Broadcasted 3D array c:")
print(c_broadcasted)


ValueError: operands could not be broadcast together with shapes (4,3) (3,1) 

In [21]:
import numpy as n
a = n.array(((1, 2, 3), (4, 5, 6), (7, 8, 9), (10, 11, 12)))
b = n.array((1, 0, 1))
# Convert b into a 2D array with the same number of rows as a
b_2d = n.tile(b, (a.shape[0], 1)) # which will repeat the values of b 1d as 4 rows .and a.shape[0]-->4 rows ,1 -->coloumn indicate
c= a + b_2d
print(" 2D array a:")
print(a)
print("\n")
print("3D array c:")
print(c)

 2D array a:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


3D array c:
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
